---
apiVersion: v1
kind: Namespace
metadata:
  name: "taxi-travel-time-prediction"

---
apiVersion: v1
kind: Namespace
metadata:
  name: "monitoring"

---
apiVersion: v1
kind: Namespace
metadata:
  name: "logging"
